AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Creates a Cloudwatch Event that triggers
  a Lambda function to create Snapshot to the
  specified Database in RDS with a custom interval

Parameters:
  RDSIdentifier:
    Description: The RDS Instance Identifier
    Type: String

  CronInterval:
    Description: Interval in cron or rate expression
    Type: String

Resources:
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Statement:
          -
            Effect: Allow
            Principal:
              Service: [lambda.amazonaws.com]
            Action: ['sts:AssumeRole']

      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
      Policies:
        - PolicyName: TakeSnapshotFunctionPolicy
          PolicyDocument:
            Statement:
              -
                Effect: Allow
                Action:
                  - 'rds:CreateDBSnapshot'
                Resource:
                  - !Join ['', ['arn:aws:rds:', !Ref "AWS::Region", ':', !Ref "AWS::AccountId", ':db:', !Ref "RDSIdentifier"]]
                  - !Join ['', ['arn:aws:rds:', !Ref "AWS::Region", ':', !Ref "AWS::AccountId", ':snapshot:*']]

  TakeSnapshotFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: 'index.handler'
      Role: !GetAtt LambdaRole.Arn
      Runtime: 'python3.7'
      Environment:
        Variables:
          RDS_ID: !Ref RDSIdentifier
      Code:
        ZipFile: |
          import boto3
          import time
          import os
          client = boto3.client('rds')

          def handler(event, context):
              id = time.strftime("%Y-%m-%d-%H-%M-%S")
              print('Taking snapshot of ' + os.getenv('RDS_ID'))

              client.create_db_snapshot(
                  DBInstanceIdentifier=os.getenv('RDS_ID'),
                  DBSnapshotIdentifier="snapshot-" + id
              )

              print('Snapshot created')
              return "OK"

  EventRule:
    Type: AWS::Events::Rule
    Properties:
      ScheduleExpression: !Ref CronInterval
      State: ENABLED
      Targets:
        -
          Id: "1"
          Arn: !GetAtt TakeSnapshotFunction.Arn

  TakeSnapshotFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties: 
      Action: 'lambda:InvokeFunction'
      FunctionName: !GetAtt TakeSnapshotFunction.Arn
      Principal: 'events.amazonaws.com'
      SourceArn: !GetAtt EventRule.Arn

